### ISSUE TITLE
Deprecate somaliar step in favour of dedicated Holmes pipeline

### ISSUE THREAD

**Issue by victorskl** [umccr/cwl-ica#145]
**Context:**

* [Holmes](https://github.com/umccr/holmes) pipeline is now running on the regular basis of end of `DRAGEN_WGS_QC` (alignment QC) and `DRAGEN_WTS` workflows. Driven by main pipeline orchestrator as follows.

https://github.com/umccr/data-portal-apis/blob/6c482073b0d04676b29c141fac55c87e242d08ff/data_processors/pipeline/lambdas/orchestrator.py#L210-L246

**Actions:**

- To deprecate relevant somaliar steps from the respective workflows

**Comment by alexiswl** [comment]
Yep we can just move to the alignment workflow for the qc pipeline. Will need to remove this step from the wts pipeline though

**Comment by skanwal** [comment]
Yep have discussed with Oliver as well, on my to-do for the next portal release.

**Comment by ohofmann** [comment]
Hijacking this issue but as a future feature request - add the ctTSO500 BAMs to the Holmes inputs.

**Comment by alexiswl** [comment]
@victorskl I think this can be closed, was resolved by https://github.com/umccr/infrastructure/commit/fe2757197faab56ce871a8951e7e1d178f754d6e

**Comment by victorskl** [comment]
Ah. Right. Yep. Closing...

**Comment by victorskl** [comment]
We might have .somalier cleanup in GDS. But. That can be part of GDS Cleanup activity. So all good, I reckon.
