### ISSUE TITLE
TSO500 ctDNA RUO bundle reference genome hg19

### ISSUE THREAD

**Issue by victorskl** [umccr/cwl-ica#153]
**Context:**

https://github.com/umccr/infrastructure/blob/b49872b88e745f96b26d95865ee6b1e6fa5bfff5/terraform/stacks/umccr_data_portal/workflow/main.tf#L344-L377

i.e.
```
gds://[development|production]/reference-data/dragen_tso_ctdna/ruo-1.1.0.3/
```

**Issues:**

- Block somalier BAM extract

**Comment by alexiswl** [comment]
@victorskl I'm not really sure there's much we can do about this. Would need to contact the ctTSO500 team to see if they have any plans on moving to hg38

**Comment by ohofmann** [comment]
Waiting for feedback from Shyamal. Here's what I asked:

> We are using https://github.com/umccr/holmes to routinely run https://github.com/brentp/somalier over (most) BAMs as they arrive. It’s one of the better frameworks for alignment-baser fingerprints and we report back any discordance (or unexpected overlaps) to a Slack channel.

> The target sites are hg38 exons to cover WGS/WTS and ideally also most larger panels, but that’s where we run into issues with ctTSO500. We’re thinking of adding a ctTSO500 post-processing workflow that lifts over reads to hg38 using https://github.com/milkschen/leviosam2 - is anyone in the DRAGEN team working on related workflows?

**Comment by alexiswl** [comment]
Also wondering if we can just run the tso data through the wgs qc alignment pipeline? Other than using another fpga for a few hours, would this be any cause for concern?

**Comment by ohofmann** [comment]
TSO or ctTSO? In either case, we'd have to make a couple of changes to the workflow (UMI handling, read collapsing) - https://github.com/fulcrumgenomics/fgbio/blob/main/docs/best-practice-consensus-pipeline.md or similar to get something meaningful out of the reads. 

I _think_ we'd only do this if we'd also wanted to generate other QC parameters. The liftover strategy would have the benefit of generating BAMs that the curators can review side-by-side with existing WGS data.

**Comment by alexiswl** [comment]
Closing since original issue `Block somalier BAM extract` is no longer blocked with new hg19.rna somalier sites file
