### ISSUE TITLE
Arriba hardware requirements seems higher than expected

### ISSUE THREAD

**Issue by alexiswl** [umccr/cwl-ica#201]
Both arriba and arriba drawing use standardHiCpu Large instances, which is 72 CPU and 140 Gb of RAM? 

Is this necessary? Reducing the requirements will reduce the amount of time we have these tasks pending

**Comment by alexiswl** [comment]
Following this up Sehrish, with the release of v1.16.3, we can use the ica-get-task-pod-metrics command to collect all of the arriba workflows and see what cpu and memory usage they're using.  

```bash

# Switch to prod context
ica-context-switcher --scope read-only --project production

# Read in all of the tasks
# Select those that are arriba tasks
# Return all arriba task ids
arriba_task_run_ids="$( \
  ica tasks runs list \
    --max-items=0 \
    --output-format=json | \
  jq --raw-output \
    '
      .items |
      map(
        select(
          .name | startswith("arriba")
        )
      ) |
      map(.id) |
      .[]
    '
)"

# Collect metrics for each task
# And collate into a json list
aggregate_metrics="$( \
  (
    for task_run_id in ${arriba_task_run_ids}; do
      ica-get-task-pod-metrics \
        --output-format json \
        --ica-task-run-id "${task_run_id}";
    done
  ) | \
  jq --slurp
)"
```

# Output values of average maximum, max maximum of all aggregate metrics
echo "Average max mem is $(jq 'map(.max_mem) | add / length' <<< "${aggregate_metrics}")"
echo "Maximum max mem is $(jq 'map(.max_mem) | max' <<< "${aggregate_metrics}")"
echo "Average max cpu is $(jq 'map(.max_cpu) | add / length' <<< "${aggregate_metrics}")"
echo "Maximum max cpu is $(jq 'map(.max_cpu) | max' <<< "${aggregate_metrics}")"
```

Which yields the following:

```
Average max mem is 4.355884615384608                                                                                                                                                                                                                                                                                                                                                          Maximum max mem is 21.35                                                                                                                                                                                                                                                                                                                                                                      Average max cpu is 0.9896153846153848                                                                                                                                                                                                                                                                                                                                                         Maximum max cpu is 1
```

Therefore I think a more appropriate node would be a 'standard large' which has a size of 2 CPU and 7 GB or a 'standard xlarge' which has a size of 4 CPU and 14 GB.  

I'm going to follow up a few of our current uses (umccrise, dragen runs etc) to see how we're tracking with those as well.  It creates a greater use-case for Illumina to show we're using these and that obtaining pod-metrics is definitely a requirement we'd like to see in ICAv2.

**Comment by skanwal** [comment]
Thanks for following it up Alexis. 
I think instead of Average, we should go with Maximum values for mem and cpu to avoid failure.

**Comment by alexiswl** [comment]
> I think instead of Average, we should go with Maximum values for mem and cpu to avoid failure.

Yep to clarify this is the average maximum, when filtering to only arriba 2.3.0 (those tasks generated after June 17) -- see https://github.com/umccr/data-portal-apis/milestone/9?closed=1 

the maximum memory usage is actually only 11 Gb.

**Comment by alexiswl** [comment]
## Script was

```bash
# Switch to prod context
ica-context-switcher --scope admin --project-name production

# Read in all of the tasks
# Select those that are arriba tasks
# Return all arriba task ids
arriba_task_run_ids="$( \
  ica tasks runs list \
    --max-items=10000 \
    --output-format=json | \
  jq --raw-output \
    '
      .items |
      map(
        select(
	  (.name | startswith("arriba")) and
	  (.timeModified > "2022-06-17")
        )
      ) |
      map(.id) |
      .[]
    '
)"

# Collect metrics for each task
# And collate into a json list
aggregate_metrics="$( \
  (
    for task_run_id in ${arriba_task_run_ids}; do
      ica-get-task-pod-metrics \
        --output-format json \
        --ica-task-run-id "${task_run_id}";
    done
  ) | \
  jq --slurp
)"

jq 'map(.max_mem) | .[]' <<< "${aggregate_metrics}" > mems.txt

( \
cat <<- EOF
clear
reset
set key off
set border 3

# Add a vertical dotted line at x=0 to show centre (mean) of distribution.
set yzeroaxis

# Each bar is half the (visual) width of its x-range.
set boxwidth 0.05 absolute
set style fill solid 1.0 noborder
set term png
set output 'arriba-230.png'

bin_width = 0.1;

bin_number(x) = floor(x/bin_width)

rounded(x) = bin_width * ( bin_number(x) + 0.5 )

# Set labels
set xlabel "Memory in GB"
set ylabel ""
unset ytics
set title "Arriba 2.3.0 usage"

plot 'mems.txt' using (rounded($1)):(1) smooth frequency with boxes
EOF
) > gnuplot.bat

gnuplot -c gnuplot.bat
```

**Comment by alexiswl** [comment]
So the standard xlarge will be fine (with 4 CPU and 14 GB RAM), and a much smaller instance footprant than the standardHiCPU (72 CPU and 140 GB RAM)

**Comment by alexiswl** [comment]
I've split this out into arriba fusion and arriba drawing plots.  

## Arriba Drawing (2.3.0)

**CPU**

![arriba_drawing cpu](https://user-images.githubusercontent.com/8197659/214966294-f22440e9-784d-4860-8aaf-a282ba9e8f52.png)


**MEM**

![arriba_drawing mem](https://user-images.githubusercontent.com/8197659/214966308-867041d1-ebdd-406f-ac93-5d4cfd39a88b.png)

**Comment by alexiswl** [comment]
## Arriba Fusion

**CPU**
![arriba_fusion cpu](https://user-images.githubusercontent.com/8197659/214966377-fa849489-73e8-4897-a888-80e19230fe1d.png)

**MEM**

![arriba_fusion mem](https://user-images.githubusercontent.com/8197659/214966391-5388e0ce-0b33-4148-925f-aab5c9df1ecb.png)
