### ISSUE TITLE
Copy STAR index from Gadi to ICA

### ISSUE THREAD

**Issue by skanwal** [umccr/cwl-ica#229]
Discussion at https://github.com/umccr/cwl-ica/pull/210

**Comment by alexiswl** [comment]
Not sure if this is a CWL issue, would it be worth seeing if we could make the STAR index on ICA? It may make the STAR alignment CWL tool useful for others

**Comment by skanwal** [comment]
> Not sure if this is a CWL issue

It's not a CWL issue but more like a enhancement for our tool definition in this repo to make it more useful.
I had created an issue so that I remember to look into it when I get a chance.

**Comment by alexiswl** [comment]
Having a look at Stephen's STAR index on Gadi,

The genomeParameters.txt file makes it pretty easy to reproduce this:

```
### STAR   --runMode genomeGenerate   --runThreadN 8   --genomeDir ./star_index/   --genomeFastaFiles data/Homo_sapiens.GRCh37.GATK.illumina.fasta      --genomeChrBinNbits 15   --limitGenomeGenerateRAM 60000000000   --sjdbGTFfile data/gencode.v19.annotation.nochrprefix.gtf   --sjdbOverhang 200
### GstrandBit 32
versionGenome   2.7.1a
genomeFastaFiles        data/Homo_sapiens.GRCh37.GATK.illumina.fasta
genomeSAindexNbases     14
genomeChrBinNbits       15
genomeSAsparseD 1
sjdbOverhang    200
sjdbFileChrStartEnd     -
sjdbGTFfile     data/gencode.v19.annotation.nochrprefix.gtf
sjdbGTFchrPrefix        -
sjdbGTFfeatureExon      exon
sjdbGTFtagExonParentTranscript  transcript_id
sjdbGTFtagExonParentGene        gene_id
sjdbInsertSave  Basic
genomeFileSizes 3234293828 24720338217
```

**Comment by alexiswl** [comment]
Can we close this? The oncoanalyser STAR alignment will be done on nextflow
