### ISSUE TITLE
Make workflows for UMCCRise and RNASum

### ISSUE THREAD

**Issue by alexiswl** [umccr/cwl-ica#247]
UMCCRise and RNASum are CommandLineTools, to allow for pack / zip tag deployment, we need them to be workflows. 

Obvious solution is to make single step workflows for each.

**Comment by skanwal** [comment]
Isn't umccrise run as part of a workflow already?

**Comment by alexiswl** [comment]
Yep part of the umccrise-with-germline-pipeline workflow, but in future we'd like to run somatic+germline then umccrise on its own
