### ISSUE TITLE
umccrise-2.2.0--0 EOF error

### ISSUE THREAD

**Issue by skanwal** [umccr/cwl-ica#315]
Getting an error with umccrise version 2.2.0 on ICA  `wfr.51b62dc29ee543ebb2b12fee5157d4ab`.

```
$ gds-view --gds-path gds://development/temp/sehrish/analysis_data/umccrise/work/logs/run_umccrise_step/try-1/task-stderr-0.log --to-stdout
Tue 04 Apr 2023 05:07:04 AM UTC: Creating parent dir for workspace in scratch
Tue 04 Apr 2023 05:07:04 AM UTC: Creating parent dir for genomes
Tue 04 Apr 2023 05:07:04 AM UTC: Extracting genomes directory into scratch space
Tue 04 Apr 2023 05:15:24 AM UTC: Placing inputs into scratch space
scripts/run-umccrise.sh: line 39: unexpected EOF while looking for matching `"'
```

Looking through the code, think it was introduced in this commit https://github.com/umccr/cwl-ica/commit/9a70db4f31aa26a793344e4d1148b430b0fbabdf at https://github.com/umccr/cwl-ica/blob/main/tools/umccrise/2.2.0--0/umccrise__2.2.0--0.cwl#L159.

**Comment by alexiswl** [comment]
Ah whoops, well spotted!
