### ISSUE TITLE
Add additional workflow parameters to umccrise

### ISSUE THREAD

**Issue by alexiswl** [umccr/cwl-ica#323]
Add the following parameters to umccrise (versions 2.2.0 and 2.2.1)

* --stage (Array of steps to run)
* --skip-stage (Array of steps to skip)
* --debug (Copy over outputs if fails)
* --dryrun (Output which stages would be run)

**Comment by skanwal** [comment]
Linking commits for this here as well

https://github.com/umccr/cwl-ica/commit/2abe23179972ae6aa3ddf21d119c5e31c451bee5
https://github.com/umccr/cwl-ica/commit/e683d4342ddfdbfa73aa6f6e934fba23378dbc73
https://github.com/umccr/cwl-ica/commit/cb1a3481c3b593a6b24f963214e447e2e8ea06f5

**Comment by alexiswl** [comment]
Probably worth putting these (and their descriptions in the PR instead). We have the PR linked to this issue via the Development Pane on the Side Bar.

![image](https://user-images.githubusercontent.com/8197659/232675727-1b86af19-67c4-4d5c-a334-e7ecbf00d3d1.png)
