### ISSUE TITLE
Arriba fusion calling - OOM error

### ISSUE THREAD

**Issue by skanwal** [umccr/cwl-ica#333]
Arriba is erroring out with OOM error in our current WTS production pipeline:

```
  "logs": [
    {
      "startTime": "2023-04-23T10:22:16.259961Z",
      "endTime": "2023-04-23T10:26:59.773401Z",
      "error": "Failed",
      "errorDetails": "OOMKilled",
      "stdout": "gds://production/temp/analysis_data/SBJ03173/wts_tumor_only/20230423e2a89bf8/logs/arriba_fusion_step/try-1/task-stdout-0.log",
      "stderr": "gds://production/temp/analysis_data/SBJ03173/wts_tumor_only/20230423e2a89bf8/logs/arriba_fusion_step/try-1/task-stderr-0.log"
    }
  ]
  ```
  Task standard error log file is empty but OOM error is stated above in `errorDetails`.
  
**Notes**

 The resource requirements were updated for Arriba couple months ago. See discussion here https://github.com/umccr/cwl-ica/issues/201. It can be noted in Arriba Fusion Max Mem Usage plot that few tasks used more than 20GB memory. We have currently set Arriba to use standard xlarge instance that has 4CPUs and 14GB max memory https://illumina.gitbook.io/ica-v1/analysis/a-taskexecution#type-and-size.
 
 Also, we have WGS contamination issue for this subject. Need to check if this is interlinked.
  
  **Next steps:**
  
  - Update Arriba tool to use standard xxlarge instance. 
  - Test in dev with L2300461
  - Update production workflow

**Comment by alexiswl** [comment]
Few other notes to add

## Failed workflow id

> wfr.1c7cd5660bdc4056af8d08e57533ebe9

## Failed task id

```
ica-get-tasks-from-workflow-history --ica-workflow-run-id wfr.1c7cd5660bdc4056af8d08e57533ebe9 | \
jq '.["/arriba_fusion_step"]'
```

Yields

```
{
  "task_id": "trn.b3baa22ac47f4e5b8fcf8801c92c18fc",
  "task_name": "arriba_fusion_step",
  "task_launch_time": "2023-04-23T10:17:17.096609Z",
  "task_completion_time": "2023-04-23T10:28:07.046603Z",
  "task_status": "Failed",
  "task_stdout": "gds://production/temp/analysis_data/SBJ03173/wts_tumor_only/20230423e2a89bf8/logs/arriba_fusion_step/try-1/task-stdout-0.log",
  "task_stderr": "gds://production/temp/analysis_data/SBJ03173/wts_tumor_only/20230423e2a89bf8/logs/arriba_fusion_step/try-1/task-stderr-0.log"
}
```

```
ica-get-task-pod-metrics --ica-task-run-id trn.b3baa22ac47f4e5b8fcf8801c92c18fc
```

Yields

```
Max CPU was: 1
Avg CPU was: 1
Max Mem was: 7.73
Avg Mem was: 5.44
```

Which doesn't quite add up. 

Could be that the pod-metrics was not updated before the task was killed. 

Worth rerunning this with an xxlarge and seeing what the max-mem value is defined as.

**Comment by skanwal** [comment]
Follow-up notes:

From lab team:

> Yes, we did notice that MDX230120 was sequenced deeper than usual.  Based on the qPCR concentration, it was loaded neat but it seems like there must have been some sought of error with the concentration (which we cannot pinpoint) and should have been diluted before loading.

Also explains why WTS bam is 40G, which is unusual for our WTS samples.

- Task fails with standard xxlarge - `trn.0fe18a35797c4aa089593770173d9148`
- Task fails with StandardHiMem small - `trn.d9eaf28709be4f768208fefff09570b9`
- Task ran successfully with StandardHiMem medium - `trn.9a3ace10c154453fb5596eaf52b89352`

The lab team is looking into re-sequencing SBJ03173 (WGS+WTS). We might still want to bump-up resources for Arriba.. tbd.

**Comment by alexiswl** [comment]
```
ica-get-task-pod-metrics --ica-task-run-id trn.9a3ace10c154453fb5596eaf52b89352
```

Yields

```
Max CPU was: 1
Avg CPU was: 1
Max Mem was: 106.79
Avg Mem was: 83.22
```

**Comment by alexiswl** [comment]
One of the APGI samples failed with this same error: 

WFR ID: wfr.a73bfcd5326b40a898b778b117f6c781
APGI ID: APGI_2302
ICGC ID: ICGC_0066

**Comment by skanwal** [comment]
Should I push updated  WTS workflow with new Arriba version to prod?

**Comment by alexiswl** [comment]
> Should I push updated WTS workflow with new Arriba version to prod?

We just need to update the tool definition to use xxlarge and it will create a new workflow version in prod

**Comment by skanwal** [comment]
> We just need to update the tool definition to use xxlarge and it will create a new workflow version in prod

I'd prefer coupling this with updated Arriba, so that we don't hit that C++ error as well/

**Comment by alexiswl** [comment]
@skanwal has this been resolved?

**Comment by skanwal** [comment]
No - the tool is still using https://github.com/umccr/cwl-ica/blob/main/tools/arriba-fusion-calling/2.4.0/arriba-fusion-calling__2.4.0.cwl#L29 in the updated arriba definition. Happy to bump up to xxlarge?
