### ISSUE TITLE
Enable HRD calling in TN workflow

### ISSUE THREAD

**Issue by skanwal** [umccr/cwl-ica#358]
Reference: https://trello.com/c/3Ww9alsI/1179-dragen-hrd-results

**Comment by alexiswl** [comment]
Related to https://github.com/umccr/infrastructure/pull/335

**Comment by victorskl** [comment]
Had turn flags on as part of Portal T/N automation input template side - ditto diff
https://github.com/umccr/infrastructure/pull/335/files

**Comment by victorskl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Portal Release - Ocicat: Add Dragen HRD results](https://trello.com/c/3Ww9alsI/1179-portal-release-ocicat-add-dragen-hrd-results)
