### ISSUE TITLE
Add cttsor step to the cttso post-processing pipeline 

### ISSUE THREAD

**Issue by alexiswl** [umccr/cwl-ica#456]
Add a step to the cttso post-processing pipeline to include the cttsoR task.  

This will comprise - 

1. Creating the cttsoR tool (this will need to accept all a set of appoximately 15 files)

2. Add the tool to the second-last step of the post-processing pipeline

3. Update the expression get-custom-output-dir-entry-for-tso500-post-processing__2.0.1.cwl

4. Update the post-processing workflow step create_custom_output_entry_list_array_step to include the cttso R outputs.  

Will likely use a file copy methid 

```javascript
get_custom_output_dir_entry_from_file_list(
    [
      inputs.cttsor_report
    ],
    null,
    "top_dir"
)
```

**Comment by pdiakumis** [comment]
We've also had a request from the curation team for PCGR to run on the merged VCF. Perhaps one for after the new PCGR version comes out.

**Comment by alexiswl** [comment]
Sure! Are you happy for this to be part of the post-processing pipeline or have it as its own downstream workflow?

**Comment by pdiakumis** [comment]
Up to you, all they want is the PCGR HTML as a 'sanity check'. Low priority, let us revisit once the new PCGR is out - should we open a different issue to keep track?

**Comment by alexiswl** [comment]
I don't think we'll get to this before we move V1 analysis to the v2 pipeline.
