### ISSUE TITLE
Revisit BCLConvert pipeline

### ISSUE THREAD

**Issue by alexiswl** [umccr/cwl-ica#564]
Emulate the BCLConvert 4.2.7 nf pipeline but swap out the bclconvert cpu hardware for dragen hardware to generate the ora files

![image](https://github.com/user-attachments/assets/b08cce09-c6b8-4081-8fda-02a5620f3453)

**Comment by alexiswl** [comment]
Nm, Illumina BSSH Autolaunch only supports nextflow pipelines.

**Comment by victorskl** [comment]
😿

**Comment by alexiswl** [comment]
Related https://github.com/umccr-illumina/ica_v2/issues/203
